"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {
    "repo_name": "Synthesis-YieldGuard-OpenTrack",
    "project_name": "YieldGuard Autonomous Public Goods Swarm",
    "track": "Open Track",
    "pitch": (
        "A yield-only autonomous public-goods swarm that discovers funding gaps, "
        "spends only staking yield through bounded delegations, stores impact "
        "proofs, publishes repo-hosted evaluation artifacts, and updates agent "
        "receipts."
    ),
    "idea_titles": [
        "YieldGuard Autonomous Public Goods Swarm",
        "ENS-Native Private Governance Swarm",
        "Lido Yield Routing Commons",
        "Proof-of-Impact Market Mesh",
    ],
    "architecture_summary": (
        "A coordinator agent scans Octant and onchain public-goods signals, "
        "routes sensitive ranking through Venice, and creates dry-run action "
        "bundles. A yield guard contract records per-target caps, time windows, "
        "and delegated execution so sub-agents can route Lido yield through "
        "Uniswap, Celo, repo-hosted Octant outputs, upload-ready Filecoin "
        "bundles, wallet-signed Locus payment intents, Olas marketplace bundles, "
        "and an onchain Slice hook without touching principal."
    ),
    "overlap_targets": [
        "Lido stETH Treasury",
        "Uniswap Agentic Finance",
        "Venice Private Agents",
        "Octant",
        "Filecoin",
        "Celo",
        "ERC-8004 Receipts",
        "Bankr Gateway",
        "MetaMask Delegations",
        "PayWithLocus",
        "ENS",
        "Olas",
        "Slice",
    ],
    "primary_contract_name": "YieldGuardTreasury",
    "primary_python_module": "yieldguard_swarm",
    "category": "public_goods",
    "daily_budget_usd": 160,
    "per_action_budget_usd": 40,
    "cooldown_seconds": 900,
    "discovery_inputs": [
        {
            "name": "project_signals",
            "description": "Impact, treasury, and opportunity signals.",
        },
        {
            "name": "private_inputs",
            "description": "Sensitive ranking inputs or reviewer context.",
        },
        {
            "name": "execution_bundle",
            "description": "Micro-grant or allocation execution plan.",
        },
        {
            "name": "receipts",
            "description": "Proofs, submission notes, and final evidence.",
        },
    ],
    "live_demo_steps": [
        "Copy .env.example to .env and fill the required keys.",
        "Start Anvil against the Sepolia fork URL in .env.",
        "Deploy YieldGuardTreasury with forge script script/Deploy.s.sol --broadcast.",
        "Deploy SliceImpactHook with forge script script/DeploySliceImpactHook.s.sol --broadcast.",
        "Run python3 scripts/run_agent.py to produce dry runs, offline artifacts, and live API calls.",
        "Run python3 scripts/render_submission.py and attach TxIDs plus repo artifact paths.",
    ],
    "partners": [
        {
            "name": "Lido",
            "docs_url": "https://docs.lido.fi/",
            "env_vars": ["RPC_URL"],
            "endpoint_env": "",
            "action_kind": "contract_call",
            "purpose": "Route staking yield through guarded treasury actions.",
        },
        {
            "name": "Uniswap",
            "docs_url": "https://developers.uniswap.org/",
            "env_vars": ["UNISWAP_API_KEY", "UNISWAP_QUOTE_URL"],
            "endpoint_env": "UNISWAP_QUOTE_URL",
            "action_kind": "rest_json",
            "purpose": "Quote swaps and bounded liquidity moves.",
        },
        {
            "name": "Venice",
            "docs_url": "https://docs.venice.ai/",
            "env_vars": [
                "VENICE_API_KEY",
                "VENICE_CHAT_COMPLETIONS_URL",
                "VENICE_MODEL",
            ],
            "endpoint_env": "VENICE_CHAT_COMPLETIONS_URL",
            "action_kind": "rest_json",
            "purpose": "Run private reasoning over sensitive inputs.",
        },
        {
            "name": "Octant",
            "docs_url": "https://docs.octant.app/en-EN/",
            "env_vars": [],
            "endpoint_env": "",
            "action_kind": "local_publish",
            "purpose": "Publish repo-hosted scored public-goods signals and DPI artifacts.",
        },
        {
            "name": "Filecoin",
            "docs_url": "https://docs.filecoin.cloud/getting-started/",
            "env_vars": [],
            "endpoint_env": "",
            "action_kind": "proof_bundle",
            "purpose": "Persist upload-ready proofs, logs, and evidence bundles.",
        },
        {
            "name": "Celo",
            "docs_url": "https://docs.celo.org/",
            "env_vars": ["CELO_RPC_URL"],
            "endpoint_env": "",
            "action_kind": "contract_call",
            "purpose": "Settle stablecoin-native transfers on Celo rails.",
        },
        {
            "name": "ERC-8004 Receipts",
            "docs_url": "https://eips.ethereum.org/EIPS/eip-8004",
            "env_vars": ["RPC_URL"],
            "endpoint_env": "",
            "action_kind": "contract_call",
            "purpose": "Anchor identity, task receipts, and reputation updates.",
        },
        {
            "name": "Bankr Gateway",
            "docs_url": "https://docs.bankr.bot/llm-gateway/overview/",
            "env_vars": [
                "BANKR_API_KEY",
                "BANKR_CHAT_COMPLETIONS_URL",
                "BANKR_MODEL",
            ],
            "endpoint_env": "BANKR_CHAT_COMPLETIONS_URL",
            "action_kind": "rest_json",
            "purpose": "Route inference through cost-aware model selection.",
        },
        {
            "name": "MetaMask Delegations",
            "docs_url": "https://docs.metamask.io/delegation-toolkit/",
            "env_vars": ["RPC_URL"],
            "endpoint_env": "",
            "action_kind": "contract_call",
            "purpose": "Enforce delegation scopes, expiries, and intent envelopes.",
        },
        {
            "name": "PayWithLocus",
            "docs_url": "https://docs.locus.finance/",
            "env_vars": [],
            "endpoint_env": "",
            "action_kind": "signed_payment",
            "purpose": "Create wallet-signed bounded subaccount payment intents.",
        },
        {
            "name": "ENS",
            "docs_url": "https://docs.ens.domains/",
            "env_vars": ["ENS_NAME"],
            "endpoint_env": "",
            "action_kind": "contract_call",
            "purpose": "Publish human-readable coordination and identity receipts.",
        },
        {
            "name": "Olas",
            "docs_url": "https://build.olas.network/hire",
            "env_vars": [],
            "endpoint_env": "",
            "action_kind": "marketplace_bundle",
            "purpose": "Prepare hire-and-monetize marketplace request bundles.",
        },
        {
            "name": "Slice",
            "docs_url": "https://github.com/slice-so/hooks",
            "env_vars": [],
            "endpoint_env": "",
            "action_kind": "hook_contract",
            "purpose": "Deploy an onchain pricing and purchase-action hook.",
        },
    ],
    "actions": [
        {
            "id": "lido_yield_route",
            "target": "lido",
            "purpose": "Route yield-only spend decisions through the treasury contract.",
            "partner": "Lido",
            "action_kind": "contract_call",
            "max_amount_usd": 200,
            "priority": 100,
            "sensitivity": "medium",
            "notes": [
                "Use Lido only after a dry-run artifact exists.",
                "Enforce principal floor and approved selectors.",
            ],
        },
        {
            "id": "uniswap_quote_route",
            "target": "uniswap",
            "purpose": "Quote a bounded treasury rebalance route.",
            "partner": "Uniswap",
            "action_kind": "rest_json",
            "max_amount_usd": 220,
            "priority": 95,
            "sensitivity": "medium",
            "notes": [
                "Quote only after a dry-run artifact exists.",
                "Use mainnet quote flow while deploying contracts on Sepolia fork.",
            ],
        },
        {
            "id": "venice_private_analysis",
            "target": "venice",
            "purpose": "Run private treasury and grant scoring analysis.",
            "partner": "Venice",
            "action_kind": "rest_json",
            "max_amount_usd": 5,
            "priority": 90,
            "sensitivity": "high",
            "notes": [
                "Sensitive ranking inputs stay inside the Venice request.",
                "Only publish summarized outputs to repo artifacts.",
            ],
        },
        {
            "id": "octant_signal_publish",
            "target": "octant",
            "purpose": "Publish repo-hosted public-goods scoring evidence.",
            "partner": "Octant",
            "action_kind": "local_publish",
            "max_amount_usd": 25,
            "priority": 85,
            "sensitivity": "medium",
            "notes": [
                "Create a weighted-signal artifact for Octant evaluation.",
                "Keep the scoring method transparent and reproducible.",
            ],
        },
        {
            "id": "filecoin_proof_store",
            "target": "filecoin",
            "purpose": "Package upload-ready evidence for Filecoin agentic storage.",
            "partner": "Filecoin",
            "action_kind": "proof_bundle",
            "max_amount_usd": 20,
            "priority": 80,
            "sensitivity": "medium",
            "notes": [
                "Produce a content-addressed bundle before testnet funding.",
                "Use Calibration faucet links for the live follow-up.",
            ],
        },
        {
            "id": "celo_payment_settle",
            "target": "celo",
            "purpose": "Prepare a cUSD settlement intent for micro-grants.",
            "partner": "Celo",
            "action_kind": "contract_call",
            "max_amount_usd": 150,
            "priority": 75,
            "sensitivity": "low",
            "notes": [
                "Use Celo rails for stablecoin-native payouts.",
                "Keep the action bounded by daily policy caps.",
            ],
        },
        {
            "id": "erc_8004_receipts_receipt_anchor",
            "target": "erc_8004_receipts",
            "purpose": "Anchor receipts and reputation updates.",
            "partner": "ERC-8004 Receipts",
            "action_kind": "contract_call",
            "max_amount_usd": 1,
            "priority": 70,
            "sensitivity": "medium",
            "notes": [
                "Anchor digest receipts after execution.",
                "Use the Synthesis registration as the identity base.",
            ],
        },
        {
            "id": "bankr_gateway_compute_route",
            "target": "bankr_gateway",
            "purpose": "Route the plan through Bankr for cost-aware inference.",
            "partner": "Bankr Gateway",
            "action_kind": "rest_json",
            "max_amount_usd": 10,
            "priority": 65,
            "sensitivity": "high",
            "notes": [
                "Use the Bankr OpenAI-compatible LLM gateway.",
                "Track inference recommendations as execution evidence.",
            ],
        },
        {
            "id": "metamask_delegations_delegate_scope",
            "target": "metamask_delegations",
            "purpose": "Prepare a delegation-scoped execution intent.",
            "partner": "MetaMask Delegations",
            "action_kind": "contract_call",
            "max_amount_usd": 2,
            "priority": 60,
            "sensitivity": "high",
            "notes": [
                "Use bounded delegation scopes and expiries.",
                "Keep the signed intent tied to the dry-run digest.",
            ],
        },
        {
            "id": "paywithlocus_subaccount_pay",
            "target": "paywithlocus",
            "purpose": "Create a signed payment intent for compute and commerce.",
            "partner": "PayWithLocus",
            "action_kind": "signed_payment",
            "max_amount_usd": 120,
            "priority": 55,
            "sensitivity": "medium",
            "notes": [
                "Use a wallet-signed bounded spend intent.",
                "Target Bankr and Slice as approved merchants.",
            ],
        },
        {
            "id": "ens_ens_publish",
            "target": "ens",
            "purpose": "Prepare ENS-linked publication receipts.",
            "partner": "ENS",
            "action_kind": "contract_call",
            "max_amount_usd": 5,
            "priority": 50,
            "sensitivity": "low",
            "notes": [
                "Publish via ENS-native identity, not hex-only labels.",
                "Use k42.radicle.eth for operator attribution.",
            ],
        },
        {
            "id": "olas_market_hire",
            "target": "olas",
            "purpose": "Create Olas marketplace hire and monetization bundles.",
            "partner": "Olas",
            "action_kind": "marketplace_bundle",
            "max_amount_usd": 20,
            "priority": 45,
            "sensitivity": "medium",
            "notes": [
                "Prepare at least ten hire requests for the same service family.",
                "Attach a monetized service description to the repo artifact.",
            ],
        },
        {
            "id": "slice_checkout_hook",
            "target": "slice",
            "purpose": "Deploy and configure a Slice checkout hook contract.",
            "partner": "Slice",
            "action_kind": "hook_contract",
            "max_amount_usd": 35,
            "priority": 40,
            "sensitivity": "medium",
            "notes": [
                "Use a dedicated onchain hook contract, not a placeholder URL.",
                "Keep pricing and purchase validation onchain and auditable.",
            ],
        },
    ],
}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
