"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-YieldGuard-OpenTrack',
 'project_name': 'YieldGuard Autonomous Public Goods Swarm',
 'track': 'Open Track',
 'pitch': 'A yield-only autonomous public-goods swarm that discovers funding gaps, '
          'spends only staking yield through bounded delegations, stores impact '
          'proofs, and updates agent receipts.',
 'idea_titles': ['YieldGuard Autonomous Public Goods Swarm',
                 'ENS-Native Private Governance Swarm',
                 'Lido Yield Routing Commons',
                 'Proof-of-Impact Market Mesh'],
 'architecture_summary': 'A coordinator agent scans Octant and onchain public-goods '
                         'signals, routes sensitive ranking through Venice, and '
                         'creates dry-run action bundles. A yield guard contract '
                         'records per-target caps, time windows, and delegated '
                         'execution so sub-agents can route Lido yield through '
                         'Uniswap, Celo, Locus, and Filecoin without touching '
                         'principal, then store proofs and update ERC-8004 receipts.',
 'overlap_targets': ['Lido stETH Treasury',
                     'Uniswap Agentic Finance',
                     'Venice Private Agents',
                     'Octant',
                     'Filecoin',
                     'Celo',
                     'ERC-8004 Receipts',
                     'Bankr Gateway',
                     'MetaMask Delegations',
                     'PayWithLocus',
                     'ENS',
                     'Olas',
                     'Slice'],
 'primary_contract_name': 'YieldGuardTreasury',
 'primary_python_module': 'yieldguard_swarm',
 'category': 'public_goods',
 'daily_budget_usd': 160,
 'per_action_budget_usd': 40,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'project_signals',
                       'description': 'Impact, treasury, and opportunity signals.'},
                      {'name': 'private_inputs',
                       'description': 'Sensitive ranking inputs or reviewer context.'},
                      {'name': 'execution_bundle',
                       'description': 'Micro-grant or allocation execution plan.'},
                      {'name': 'receipts',
                       'description': 'Proofs, submission notes, and final evidence.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for YieldGuardTreasury.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'yieldguard_swarm.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Lido',
               'docs_url': 'https://docs.lido.fi/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Route staking yield through guarded treasury actions.'},
              {'name': 'Uniswap',
               'docs_url': 'https://developers.uniswap.org/',
               'env_vars': ['UNISWAP_API_KEY', 'UNISWAP_QUOTE_URL'],
               'endpoint_env': 'UNISWAP_QUOTE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Quote swaps and bounded liquidity moves.'},
              {'name': 'Venice',
               'docs_url': 'https://docs.venice.ai/',
               'env_vars': ['VENICE_API_KEY',
                            'VENICE_CHAT_COMPLETIONS_URL',
                            'VENICE_MODEL'],
               'endpoint_env': 'VENICE_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Run private reasoning over sensitive inputs.'},
              {'name': 'Octant',
               'docs_url': 'https://octant.app/',
               'env_vars': ['OCTANT_SIGNAL_URL'],
               'endpoint_env': 'OCTANT_SIGNAL_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish scored public-goods signals and DPI artifacts.'},
              {'name': 'Filecoin',
               'docs_url': 'https://docs.filecoin.cloud/',
               'env_vars': ['FILECOIN_API_TOKEN', 'FILECOIN_UPLOAD_URL'],
               'endpoint_env': 'FILECOIN_UPLOAD_URL',
               'action_kind': 'file_upload',
               'purpose': 'Persist proofs, logs, and evidence bundles offchain.'},
              {'name': 'Celo',
               'docs_url': 'https://docs.celo.org/',
               'env_vars': ['CELO_RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Settle stablecoin-native transfers on Celo rails.'},
              {'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'},
              {'name': 'Bankr Gateway',
               'docs_url': 'https://bankr.bot/',
               'env_vars': ['BANKR_API_KEY',
                            'BANKR_CHAT_COMPLETIONS_URL',
                            'BANKR_MODEL'],
               'endpoint_env': 'BANKR_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Route inference through cost-aware model selection.'},
              {'name': 'MetaMask Delegations',
               'docs_url': 'https://docs.metamask.io/delegation-toolkit/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Enforce delegation scopes, expiries, and intent envelopes.'},
              {'name': 'PayWithLocus',
               'docs_url': 'https://docs.locus.finance/',
               'env_vars': ['LOCUS_API_KEY', 'LOCUS_PAYMENT_URL'],
               'endpoint_env': 'LOCUS_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Create bounded subaccounts and controlled spend flows.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity receipts.'},
              {'name': 'Olas',
               'docs_url': 'https://docs.olas.network/',
               'env_vars': ['OLAS_API_KEY', 'OLAS_REQUEST_URL'],
               'endpoint_env': 'OLAS_REQUEST_URL',
               'action_kind': 'rest_json',
               'purpose': 'Hire and serve marketplace requests with receipts.'},
              {'name': 'Slice',
               'docs_url': 'https://docs.slice.so/',
               'env_vars': ['SLICE_API_KEY', 'SLICE_HOOK_URL'],
               'endpoint_env': 'SLICE_HOOK_URL',
               'action_kind': 'rest_json',
               'purpose': 'Drive checkout hooks and storefront policy changes.'}],
 'actions': [{'id': 'lido_yield_route',
              'target': 'lido',
              'purpose': 'Use Lido for a bounded action in this repo.',
              'partner': 'Lido',
              'action_kind': 'contract_call',
              'max_amount_usd': 200,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call Lido only after a dry-run artifact exists.',
                        'Use https://docs.lido.fi/ for credential setup.']},
             {'id': 'uniswap_quote_route',
              'target': 'uniswap',
              'purpose': 'Use Uniswap for a bounded action in this repo.',
              'partner': 'Uniswap',
              'action_kind': 'rest_json',
              'max_amount_usd': 220,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call Uniswap only after a dry-run artifact exists.',
                        'Use https://developers.uniswap.org/ for credential setup.']},
             {'id': 'venice_private_analysis',
              'target': 'venice',
              'purpose': 'Use Venice for a bounded action in this repo.',
              'partner': 'Venice',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 90,
              'sensitivity': 'high',
              'notes': ['Call Venice only after a dry-run artifact exists.',
                        'Use https://docs.venice.ai/ for credential setup.']},
             {'id': 'octant_signal_publish',
              'target': 'octant',
              'purpose': 'Use Octant for a bounded action in this repo.',
              'partner': 'Octant',
              'action_kind': 'rest_json',
              'max_amount_usd': 25,
              'priority': 85,
              'sensitivity': 'medium',
              'notes': ['Call Octant only after a dry-run artifact exists.',
                        'Use https://octant.app/ for credential setup.']},
             {'id': 'filecoin_proof_store',
              'target': 'filecoin',
              'purpose': 'Use Filecoin for a bounded action in this repo.',
              'partner': 'Filecoin',
              'action_kind': 'file_upload',
              'max_amount_usd': 20,
              'priority': 80,
              'sensitivity': 'medium',
              'notes': ['Call Filecoin only after a dry-run artifact exists.',
                        'Use https://docs.filecoin.cloud/ for credential setup.']},
             {'id': 'celo_payment_settle',
              'target': 'celo',
              'purpose': 'Use Celo for a bounded action in this repo.',
              'partner': 'Celo',
              'action_kind': 'contract_call',
              'max_amount_usd': 150,
              'priority': 75,
              'sensitivity': 'low',
              'notes': ['Call Celo only after a dry-run artifact exists.',
                        'Use https://docs.celo.org/ for credential setup.']},
             {'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 70,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']},
             {'id': 'bankr_gateway_compute_route',
              'target': 'bankr_gateway',
              'purpose': 'Use Bankr Gateway for a bounded action in this repo.',
              'partner': 'Bankr Gateway',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 65,
              'sensitivity': 'high',
              'notes': ['Call Bankr Gateway only after a dry-run artifact exists.',
                        'Use https://bankr.bot/ for credential setup.']},
             {'id': 'metamask_delegations_delegate_scope',
              'target': 'metamask_delegations',
              'purpose': 'Use MetaMask Delegations for a bounded action in this repo.',
              'partner': 'MetaMask Delegations',
              'action_kind': 'contract_call',
              'max_amount_usd': 2,
              'priority': 60,
              'sensitivity': 'high',
              'notes': ['Call MetaMask Delegations only after a dry-run artifact '
                        'exists.',
                        'Use https://docs.metamask.io/delegation-toolkit/ for '
                        'credential setup.']},
             {'id': 'paywithlocus_subaccount_pay',
              'target': 'paywithlocus',
              'purpose': 'Use PayWithLocus for a bounded action in this repo.',
              'partner': 'PayWithLocus',
              'action_kind': 'rest_json',
              'max_amount_usd': 120,
              'priority': 55,
              'sensitivity': 'medium',
              'notes': ['Call PayWithLocus only after a dry-run artifact exists.',
                        'Use https://docs.locus.finance/ for credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 50,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']},
             {'id': 'olas_market_hire',
              'target': 'olas',
              'purpose': 'Use Olas for a bounded action in this repo.',
              'partner': 'Olas',
              'action_kind': 'rest_json',
              'max_amount_usd': 20,
              'priority': 45,
              'sensitivity': 'medium',
              'notes': ['Call Olas only after a dry-run artifact exists.',
                        'Use https://docs.olas.network/ for credential setup.']},
             {'id': 'slice_checkout_hook',
              'target': 'slice',
              'purpose': 'Use Slice for a bounded action in this repo.',
              'partner': 'Slice',
              'action_kind': 'rest_json',
              'max_amount_usd': 35,
              'priority': 40,
              'sensitivity': 'medium',
              'notes': ['Call Slice only after a dry-run artifact exists.',
                        'Use https://docs.slice.so/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
